config/routes.rb
Rails.application.routes.draw do
  
  delete "logout", to: "sessions#destroy"
  resources :tasks
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create]
  root to: "tasks#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
  validates :status, presence: true, length: {maximum: 10} 
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :name, presence:true, length: {maximum: 50}
     validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
                    
    has_many :tasks                
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    
    private
    def require_user_logged_in
        unless logged_in?
          redirect_to new_session_url
        end
    end     
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = "ログインしました"
      redirect_to root_url
    else
      flash.now[:danger] = "ログインに失敗しました"
      render "new"
    end  
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました"
    redirect_to root_url
  end
  
  private
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :require_user_logged_in
    before_action :correct_user, only: [:destroy, :edit, :show, :update]
    
    def index
        @tasks = current_user.tasks.order(id: :desc)
    end
    
    def show
        @task = Task.find(params[:id])
    end
    
    def new
        @task = current_user.tasks.build
    end
    
    def create
        @task = current_user.tasks.build(task_params)
        if @task.save
            flash[:success] = "正常に投稿されました"
            redirect_to @task
        else
            flash.now[:danger] = "投稿できませんでした"
            render :new
        end    
    end
    
    def edit
        @task = Task.find(params[:id])
    end
    
    def update
        @task = Task.find(params[:id])
        if @task.update(task_params)
            flash[:success] = "更新されました"
            redirect_to @task
        else
            flash[:danger] = "更新されませんでした"
            render :edit
        end    
    end
    
    def destroy
        @task = Task.find(params[:id])
        @task.destroy
        flash[:success] = "削除されました"
        redirect_to tasks_url
    end 
    
    private
    def task_params
        params.require(:task).permit(:content, :status)
    end 
    
    def correct_user
        @task = current_user.tasks.find_by(id: params[:id])
        unless @task
            redirect_to root_url
        end
    end    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザを登録しました"
      redirect_to root_url
    else
      flash.now[:danger] = "ユーザの登録に失敗しました"
      render :new
    end  
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def current_user
       @current_user ||= User.find_by(id: session[:user_id])
   end
   
   def logged_in?
       !!current_user
   end
end   

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |task_type, task| %>
 
 <div class="alert alert-<%= task_type %>">
   <%= task %>
 </div>
 
 <% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand navbar-light bg-light">
    <a href="/" class="navbar-brand">TaskList</a>
<% if logged_in? %>
<div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
<ul class="navbar-nav">
    <li class="nav-item">
        <%= link_to "新規タスク作成", new_task_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
        <%= link_to "ログアウト", logout_path, method: :delete, class: "nav-link" %>
    </li>
</ul>
</div>

<% else %>
<div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
<ul class="navbar-nav">
    <li class="nav-item">
        <%= link_to "新規タスク作成", new_task_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
        <%= link_to "新規ユーザ登録", new_user_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
        <%= link_to "ログイン", new_session_path, class: "nav-link" %>
    </li>
</ul>
</div>
<% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
        <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    <%= render "layouts/navbar" %>
    <div class="container">
      <%= render "layouts/flash_tasks" %>
      <%= yield %>
    </div>  
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-6">
<%= form_with(model: task, local: true) do |f| %>

<% if task.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% task.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<div class="form-group">
<%= f.label :status, "ステータス" %>
<%= f.text_field :status, class: "form-control" %>
</div>
<div class="form-group">
<%= f.label :content, "タスク" %>
<%= f.text_field :content, class: "form-control" %>
</div>
<%= f.submit "投稿", class: "btn btn-primary" %>
<% end %>
</div>
</div>

app/views/tasks/edit.html.erb
<h1>id:<%= @task.id %>のタスク編集ページ</h1>

<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>


<table class="table table-striped table-bordered">
    <tr>
        <th>id</th>
        <th>ステータス</th>
        <th>タスク</th>
    </tr>
    <% @tasks.each do |task| %>
    <tr>
        <td><%=link_to task.id, task %></td>
        <td><%= task.status %></td>
        <td><%= task.content %></td>
    </tr>
    <% end %>
</table>
    
   

app/views/tasks/new.html.erb
<h1>新規タスク投稿ページ</h1>

<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1>id:<%= @task.id %>タスクの詳細</h1>

<table class="table table-striped" >
    <tr>
        <th>id</th>
        <td><%= @task.id %></td>
    </tr>
    <tr>
        <th>ステータス</th>
        <td><%= @task.status %></td>
    </tr>
    <tr>
        <th>タスク</th>
        <td><%= @task.content %></td>
    </tr>
</table>


<%= link_to "このタスクを編集する", edit_task_path(@task), class: "btn btn-light" %>
<%= link_to "このタスクを削除する", @task, method: :delete, data: {confirm: "本当に削除していいですか？"}, class: "btn btn-danger" %>

app/views/users/new.html.erb
<h1>ユーザの新規登録</h1>

<%= form_with(model: @user, local: true) do |f| %>

<% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>


<%= f.label :name, "Name" %>
<%= f.text_field :name %>

<%= f.label :email, "Email" %>
<%= f.email_field :email %>

<%= f.label :password, "Password" %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation %>

<%= f.submit "新規作成" %>

<% end %>